package com.example.util

/**
 * Global Multi-Language Localization Engine for Localiiiy.
 * Provides instant translation dictionaries and localized strings
 * for international distribution across North America, Latin America, Europe,
 * Asia-Pacific, Africa, and the Middle East.
 */
enum class LocaliiiyLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flag: String,
    val isRtl: Boolean = false
) {
    EN("en", "English", "English (US)", "🇺🇸"),
    ES("es", "Spanish", "Español", "🇪🇸"),
    FR("fr", "French", "Français", "🇫🇷"),
    DE("de", "German", "Deutsch", "🇩🇪"),
    HI("hi", "Hindi", "हिन्दी", "🇮🇳"),
    ZH("zh", "Chinese", "中文 (简体)", "🇨🇳"),
    JA("ja", "Japanese", "日本語", "🇯🇵"),
    PT("pt", "Portuguese", "Português", "🇧🇷"),
    AR("ar", "Arabic", "العربية", "🇸🇦", isRtl = true),
    RU("ru", "Russian", "Русский", "🇷🇺"),
    BN("bn", "Bengali", "বাংলা", "🇧🇩"),
    ID("id", "Indonesian", "Bahasa Indonesia", "🇮🇩"),
    KO("ko", "Korean", "한국어", "🇰🇷"),
    IT("it", "Italian", "Italiano", "🇮🇹"),
    TR("tr", "Turkish", "Türkçe", "🇹🇷"),
    SW("sw", "Swahili", "Kiswahili", "🇰🇪"),
    VI("vi", "Vietnamese", "Tiếng Việt", "🇻🇳"),
    UR("ur", "Urdu", "اردو", "🇵🇰", isRtl = true);

    companion object {
        val ALL: List<LocaliiiyLanguage> = entries.toList()

        fun fromCode(code: String?): LocaliiiyLanguage {
            if (code.isNullOrBlank()) return EN
            return entries.find { it.code.equals(code, ignoreCase = true) } ?: EN
        }
    }
}

enum class LocaliiiyStringKey {
    // Navigation Tabs
    TAB_FEED,
    TAB_RADAR,
    TAB_MARKET,
    TAB_STUDIO,
    TAB_CLIPS,
    TAB_PROFILE,
    TAB_CREATE,

    // Header & Actions
    APP_NAME,
    SEARCH_HINT,
    NOTIFICATIONS,
    DIRECT_MESSAGES,
    GLOBAL_SETTINGS,
    CURRENCY_AND_LANG,

    // Monetization & Ads
    CREATOR_STUDIO,
    MONETIZATION_ACTIVE,
    ESTIMATED_EARNINGS,
    AD_REVENUE_SHARE,
    IN_STREAM_VIDEO_ADS,
    FEED_SPONSORED_ADS,
    SUPER_THANKS_TIPS,
    MARKETPLACE_SALES,
    REQUEST_PAYOUT,
    PAYOUT_METHODS,
    BOOST_POST,
    CREATE_AD_CAMPAIGN,
    PLATFORM_METRICS,
    MONETIZED_VIEWS,
    AVERAGE_CPM,
    LIFETIME_REVENUE,

    // Marketplace
    BUY_AND_SELL,
    LIST_ITEM,
    PRICE,
    CONDITION,
    CONTACT_SELLER,
    MAKE_OFFER,
    VERIFIED_SELLER,

    // Privacy & Security
    GHOST_MODE,
    RADAR_PULSE,
    LEGAL_POLICY,
    LOG_OUT,
    DELETE_ACCOUNT,

    // Social Actions
    LIKE,
    COMMENT,
    SHARE,
    SAVE,
    FOLLOW,
    WAVE,
    SPONSORED_LABEL
}

object LocalizationHelper {

    private val translations: Map<LocaliiiyStringKey, Map<LocaliiiyLanguage, String>> = mapOf(
        LocaliiiyStringKey.TAB_FEED to mapOf(
            LocaliiiyLanguage.EN to "Feed",
            LocaliiiyLanguage.ES to "Inicio",
            LocaliiiyLanguage.FR to "Fil",
            LocaliiiyLanguage.DE to "Feed",
            LocaliiiyLanguage.HI to "फ़ीड",
            LocaliiiyLanguage.ZH to "动态",
            LocaliiiyLanguage.JA to "フィード",
            LocaliiiyLanguage.PT to "Feed",
            LocaliiiyLanguage.AR to "الرئيسية",
            LocaliiiyLanguage.RU to "Лента",
            LocaliiiyLanguage.BN to "ফিড",
            LocaliiiyLanguage.ID to "Beranda",
            LocaliiiyLanguage.KO to "피드",
            LocaliiiyLanguage.IT to "Feed",
            LocaliiiyLanguage.TR to "Akış",
            LocaliiiyLanguage.SW to "Mlisho",
            LocaliiiyLanguage.VI to "Bảng tin",
            LocaliiiyLanguage.UR to "فیڈ"
        ),
        LocaliiiyStringKey.TAB_RADAR to mapOf(
            LocaliiiyLanguage.EN to "Radar",
            LocaliiiyLanguage.ES to "Radar",
            LocaliiiyLanguage.FR to "Radar",
            LocaliiiyLanguage.DE to "Radar",
            LocaliiiyLanguage.HI to "रडार",
            LocaliiiyLanguage.ZH to "雷达",
            LocaliiiyLanguage.JA to "レーダー",
            LocaliiiyLanguage.PT to "Radar",
            LocaliiiyLanguage.AR to "رادار",
            LocaliiiyLanguage.RU to "Радар",
            LocaliiiyLanguage.BN to "রাডার",
            LocaliiiyLanguage.ID to "Radar",
            LocaliiiyLanguage.KO to "레이더",
            LocaliiiyLanguage.IT to "Radar",
            LocaliiiyLanguage.TR to "Radar",
            LocaliiiyLanguage.SW to "Rada",
            LocaliiiyLanguage.VI to "Radar",
            LocaliiiyLanguage.UR to "ریڈار"
        ),
        LocaliiiyStringKey.TAB_MARKET to mapOf(
            LocaliiiyLanguage.EN to "Market",
            LocaliiiyLanguage.ES to "Mercado",
            LocaliiiyLanguage.FR to "Marché",
            LocaliiiyLanguage.DE to "Marktplatz",
            LocaliiiyLanguage.HI to "बाज़ार",
            LocaliiiyLanguage.ZH to "集市",
            LocaliiiyLanguage.JA to "マーケット",
            LocaliiiyLanguage.PT to "Mercado",
            LocaliiiyLanguage.AR to "السوق",
            LocaliiiyLanguage.RU to "Рынок",
            LocaliiiyLanguage.BN to "মার্কেট",
            LocaliiiyLanguage.ID to "Pasar",
            LocaliiiyLanguage.KO to "마켓",
            LocaliiiyLanguage.IT to "Mercato",
            LocaliiiyLanguage.TR to "Pazar",
            LocaliiiyLanguage.SW to "Soko",
            LocaliiiyLanguage.VI to "Chợ",
            LocaliiiyLanguage.UR to "مارکیٹ"
        ),
        LocaliiiyStringKey.TAB_STUDIO to mapOf(
            LocaliiiyLanguage.EN to "Studio",
            LocaliiiyLanguage.ES to "Estudio",
            LocaliiiyLanguage.FR to "Studio",
            LocaliiiyLanguage.DE to "Studio",
            LocaliiiyLanguage.HI to "स्टूडियो",
            LocaliiiyLanguage.ZH to "工作室",
            LocaliiiyLanguage.JA to "スタジオ",
            LocaliiiyLanguage.PT to "Estúdio",
            LocaliiiyLanguage.AR to "استوديو",
            LocaliiiyLanguage.RU to "Студия",
            LocaliiiyLanguage.BN to "স্টুডিও",
            LocaliiiyLanguage.ID to "Studio",
            LocaliiiyLanguage.KO to "스튜디오",
            LocaliiiyLanguage.IT to "Studio",
            LocaliiiyLanguage.TR to "Stüdyo",
            LocaliiiyLanguage.SW to "Studio",
            LocaliiiyLanguage.VI to "Studio",
            LocaliiiyLanguage.UR to "اسٹوڈیو"
        ),
        LocaliiiyStringKey.TAB_CLIPS to mapOf(
            LocaliiiyLanguage.EN to "Clips",
            LocaliiiyLanguage.ES to "Clips",
            LocaliiiyLanguage.FR to "Clips",
            LocaliiiyLanguage.DE to "Clips",
            LocaliiiyLanguage.HI to "क्लिप्स",
            LocaliiiyLanguage.ZH to "短视频",
            LocaliiiyLanguage.JA to "クリップ",
            LocaliiiyLanguage.PT to "Clipes",
            LocaliiiyLanguage.AR to "مقاطع",
            LocaliiiyLanguage.RU to "Клипы",
            LocaliiiyLanguage.BN to "ক্লিপস",
            LocaliiiyLanguage.ID to "Klip",
            LocaliiiyLanguage.KO to "클립",
            LocaliiiyLanguage.IT to "Clip",
            LocaliiiyLanguage.TR to "Klipler",
            LocaliiiyLanguage.SW to "Klipu",
            LocaliiiyLanguage.VI to "Thước phim",
            LocaliiiyLanguage.UR to "کلپس"
        ),
        LocaliiiyStringKey.TAB_PROFILE to mapOf(
            LocaliiiyLanguage.EN to "Profile",
            LocaliiiyLanguage.ES to "Perfil",
            LocaliiiyLanguage.FR to "Profil",
            LocaliiiyLanguage.DE to "Profil",
            LocaliiiyLanguage.HI to "प्रोफ़ाइल",
            LocaliiiyLanguage.ZH to "个人中心",
            LocaliiiyLanguage.JA to "プロフィール",
            LocaliiiyLanguage.PT to "Perfil",
            LocaliiiyLanguage.AR to "الملف الشخصي",
            LocaliiiyLanguage.RU to "Профиль",
            LocaliiiyLanguage.BN to "প্রোফাইল",
            LocaliiiyLanguage.ID to "Profil",
            LocaliiiyLanguage.KO to "프로필",
            LocaliiiyLanguage.IT to "Profilo",
            LocaliiiyLanguage.TR to "Profil",
            LocaliiiyLanguage.SW to "Wasifu",
            LocaliiiyLanguage.VI to "Hồ sơ",
            LocaliiiyLanguage.UR to "پروفائل"
        ),
        LocaliiiyStringKey.CREATOR_STUDIO to mapOf(
            LocaliiiyLanguage.EN to "Creator Studio & Monetization",
            LocaliiiyLanguage.ES to "Estudio de Creadores y Monetización",
            LocaliiiyLanguage.FR to "Studio Créateur et Monétisation",
            LocaliiiyLanguage.DE to "Creator Studio & Monetarisierung",
            LocaliiiyLanguage.HI to "क्रिएटर स्टूडियो और मुद्रीकरण",
            LocaliiiyLanguage.ZH to "创作者工作室与变现",
            LocaliiiyLanguage.JA to "クリエイタースタジオ＆収益化",
            LocaliiiyLanguage.PT to "Estúdio de Criadores e Monetização",
            LocaliiiyLanguage.AR to "استوديو المبدعين والربح",
            LocaliiiyLanguage.RU to "Творческая студия и монетизация",
            LocaliiiyLanguage.BN to "নির্মাতা স্টুডিও ও আয়",
            LocaliiiyLanguage.ID to "Studio Kreator & Monetisasi",
            LocaliiiyLanguage.KO to "크리에이터 스튜디오 및 수익 창출",
            LocaliiiyLanguage.IT to "Studio Creator e Monetizzazione",
            LocaliiiyLanguage.TR to "İçerik Stüdyosu ve Para Kazanma",
            LocaliiiyLanguage.SW to "Studio ya Wabunifu na Mapato",
            LocaliiiyLanguage.VI to "Studio sáng tạo & Kiếm tiền",
            LocaliiiyLanguage.UR to "کریئیٹر اسٹوڈیو اور کمائی"
        ),
        LocaliiiyStringKey.MONETIZATION_ACTIVE to mapOf(
            LocaliiiyLanguage.EN to "Monetization Active 🟢",
            LocaliiiyLanguage.ES to "Monetización Activa 🟢",
            LocaliiiyLanguage.FR to "Monétisation Active 🟢",
            LocaliiiyLanguage.DE to "Monetarisierung Aktiv 🟢",
            LocaliiiyLanguage.HI to "मुद्रीकरण सक्रिय 🟢",
            LocaliiiyLanguage.ZH to "变现已开启 🟢",
            LocaliiiyLanguage.JA to "収益化有効 🟢",
            LocaliiiyLanguage.PT to "Monetização Ativa 🟢",
            LocaliiiyLanguage.AR to "الربح مفعّل 🟢",
            LocaliiiyLanguage.RU to "Монетизация активна 🟢",
            LocaliiiyLanguage.BN to "আয় সক্রিয় 🟢",
            LocaliiiyLanguage.ID to "Monetisasi Aktif 🟢",
            LocaliiiyLanguage.KO to "수익 창출 활성 🟢",
            LocaliiiyLanguage.IT to "Monetizzazione Attiva 🟢",
            LocaliiiyLanguage.TR to "Para Kazanma Aktif 🟢",
            LocaliiiyLanguage.SW to "Mapato Yanafanya Kazi 🟢",
            LocaliiiyLanguage.VI to "Đang kiếm tiền 🟢",
            LocaliiiyLanguage.UR to "کمائی فعال 🟢"
        ),
        LocaliiiyStringKey.ESTIMATED_EARNINGS to mapOf(
            LocaliiiyLanguage.EN to "Estimated Earnings",
            LocaliiiyLanguage.ES to "Ganancias Estimadas",
            LocaliiiyLanguage.FR to "Revenus Estimés",
            LocaliiiyLanguage.DE to "Geschätzte Einnahmen",
            LocaliiiyLanguage.HI to "अनुमानित कमाई",
            LocaliiiyLanguage.ZH to "预估收益",
            LocaliiiyLanguage.JA to "推定収益",
            LocaliiiyLanguage.PT to "Ganhos Estimados",
            LocaliiiyLanguage.AR to "الأرباح المقدرة",
            LocaliiiyLanguage.RU to "Расчетный доход",
            LocaliiiyLanguage.BN to "আনুমানিক উপার্জন",
            LocaliiiyLanguage.ID to "Estimasi Pendapatan",
            LocaliiiyLanguage.KO to "예상 수익",
            LocaliiiyLanguage.IT to "Entrate Stimate",
            LocaliiiyLanguage.TR to "Tahmini Kazanç",
            LocaliiiyLanguage.SW to "Mapato Yanayokadiriwa",
            LocaliiiyLanguage.VI to "Doanh thu ước tính",
            LocaliiiyLanguage.UR to "تخمینی آمدنی"
        ),
        LocaliiiyStringKey.AD_REVENUE_SHARE to mapOf(
            LocaliiiyLanguage.EN to "Ad Revenue Share (55% Creator / 45% Platform)",
            LocaliiiyLanguage.ES to "Reparto de Ingresos Publicitarios (55% Creador / 45% Plataforma)",
            LocaliiiyLanguage.FR to "Partage des Revenus Publicitaires (55% Créateur / 45% Plateforme)",
            LocaliiiyLanguage.DE to "Werbeeinnahmen-Beteiligung (55% Creator / 45% Plattform)",
            LocaliiiyLanguage.HI to "विज्ञापन राजस्व हिस्सा (55% क्रिएटर / 45% प्लेटफ़ॉर्म)",
            LocaliiiyLanguage.ZH to "广告收益分成 (55% 创作者 / 45% 平台)",
            LocaliiiyLanguage.JA to "広告収益シェア (クリエイター 55% / プラットフォーム 45%)",
            LocaliiiyLanguage.PT to "Divisão de Receita de Anúncios (55% Criador / 45% Plataforma)",
            LocaliiiyLanguage.AR to "حصة إيرادات الإعلانات (55% للمبدع / 45% للمنصة)",
            LocaliiiyLanguage.RU to "Доля от рекламы (55% автору / 45% платформе)",
            LocaliiiyLanguage.BN to "বিজ্ঞাপন রাজস্ব শেয়ার (৫৫% নির্মাতা / ৪৫% প্ল্যাটফর্ম)",
            LocaliiiyLanguage.ID to "Bagi Hasil Iklan (55% Kreator / 45% Platform)",
            LocaliiiyLanguage.KO to "광고 수익 배분 (크리에이터 55% / 플랫폼 45%)",
            LocaliiiyLanguage.IT to "Ripartizione Ricavi Pubblicitari (55% Creator / 45% Piattaforma)",
            LocaliiiyLanguage.TR to "Reklam Geliri Paylaşımı (%55 İçerik Üretici / %45 Platform)",
            LocaliiiyLanguage.SW to "Gawio la Mapato ya Matangazo (55% Mbunifu / 45% Jukwaa)",
            LocaliiiyLanguage.VI to "Chia sẻ doanh thu quảng cáo (55% Tác giả / 45% Nền tảng)",
            LocaliiiyLanguage.UR to "اشتہاری آمدنی کا حصہ (55٪ تخلیق کار / 45٪ پلیٹ فارم)"
        ),
        LocaliiiyStringKey.REQUEST_PAYOUT to mapOf(
            LocaliiiyLanguage.EN to "Request Payout",
            LocaliiiyLanguage.ES to "Solicitar Pago",
            LocaliiiyLanguage.FR to "Demander le Virement",
            LocaliiiyLanguage.DE to "Auszahlung Anfordern",
            LocaliiiyLanguage.HI to "भुगतान का अनुरोध करें",
            LocaliiiyLanguage.ZH to "申请提现",
            LocaliiiyLanguage.JA to "出金を申請する",
            LocaliiiyLanguage.PT to "Solicitar Pagamento",
            LocaliiiyLanguage.AR to "طلب سحب الأرباح",
            LocaliiiyLanguage.RU to "Запросить выплату",
            LocaliiiyLanguage.BN to "টাকা তোলার অনুরোধ",
            LocaliiiyLanguage.ID to "Tarik Saldo",
            LocaliiiyLanguage.KO to "지급 요청",
            LocaliiiyLanguage.IT to "Richiedi Pagamento",
            LocaliiiyLanguage.TR to "Ödeme Talep Et",
            LocaliiiyLanguage.SW to "Omba Malipo",
            LocaliiiyLanguage.VI to "Yêu cầu thanh toán",
            LocaliiiyLanguage.UR to "رقم نکلوانے کی درخواست"
        ),
        LocaliiiyStringKey.PAYOUT_METHODS to mapOf(
            LocaliiiyLanguage.EN to "Global Payout Methods (Stripe, PayPal, Wire, UPI, Pix)",
            LocaliiiyLanguage.ES to "Métodos de Pago Globales (Stripe, PayPal, Transferencia, UPI, Pix)",
            LocaliiiyLanguage.FR to "Moyens de Paiement Mondiaux (Stripe, PayPal, Virement, UPI, Pix)",
            LocaliiiyLanguage.DE to "Globale Auszahlungsmethoden (Stripe, PayPal, Bank, UPI, Pix)",
            LocaliiiyLanguage.HI to "वैश्विक भुगतान विधियाँ (Stripe, PayPal, बैंक वायर, UPI, Pix)",
            LocaliiiyLanguage.ZH to "全球收款方式 (Stripe, PayPal, 电汇, UPI, Pix)",
            LocaliiiyLanguage.JA to "グローバル出金方法 (Stripe, PayPal, 送金, UPI, Pix)",
            LocaliiiyLanguage.PT to "Métodos de Pagamento Globais (Stripe, PayPal, Pix, Transferência)",
            LocaliiiyLanguage.AR to "طرق الدفع العالمية (Stripe, PayPal, تحويل بنكي, UPI, Pix)",
            LocaliiiyLanguage.RU to "Способы вывода по всему миру (Stripe, PayPal, Банк, UPI, Pix)",
            LocaliiiyLanguage.BN to "গ্লোবাল পেমেন্ট মেথড (Stripe, PayPal, ব্যাংক, UPI, Pix)",
            LocaliiiyLanguage.ID to "Metode Pembayaran Global (Stripe, PayPal, Transfer, UPI, Pix)",
            LocaliiiyLanguage.KO to "글로벌 정산 방식 (Stripe, PayPal, 계좌이체, UPI, Pix)",
            LocaliiiyLanguage.IT to "Metodi di Pagamento Globali (Stripe, PayPal, Bonifico, UPI, Pix)",
            LocaliiiyLanguage.TR to "Küresel Ödeme Yöntemleri (Stripe, PayPal, Havale, UPI, Pix)",
            LocaliiiyLanguage.SW to "Njia za Malipo Ulimwenguni (Stripe, PayPal, Benki, UPI, Pix)",
            LocaliiiyLanguage.VI to "Phương thức thanh toán quốc tế (Stripe, PayPal, Chuyển khoản, UPI, Pix)",
            LocaliiiyLanguage.UR to "عالمی ادائیگی کے طریقے (Stripe, PayPal, بینک, UPI, Pix)"
        ),
        LocaliiiyStringKey.BOOST_POST to mapOf(
            LocaliiiyLanguage.EN to "Boost Post / Run Ads",
            LocaliiiyLanguage.ES to "Promocionar Publicación / Anunciar",
            LocaliiiyLanguage.FR to "Booster la Publication / Pub",
            LocaliiiyLanguage.DE to "Beitrag Bewerben / Anzeigen",
            LocaliiiyLanguage.HI to "पोस्ट बूस्ट करें / विज्ञापन चलाएं",
            LocaliiiyLanguage.ZH to "推广帖子 / 投放广告",
            LocaliiiyLanguage.JA to "投稿を宣伝 / 広告配信",
            LocaliiiyLanguage.PT to "Impulsionar Publicação / Anúncios",
            LocaliiiyLanguage.AR to "ترويج المنشور / إعلانات",
            LocaliiiyLanguage.RU to "Продвигать публикацию / Реклама",
            LocaliiiyLanguage.BN to "পোস্ট বুস্ট করুন / বিজ্ঞাপন",
            LocaliiiyLanguage.ID to "Promosikan Postingan / Iklan",
            LocaliiiyLanguage.KO to "게시물 홍보 / 광고 실행",
            LocaliiiyLanguage.IT to "Promuovi Post / Pubblicità",
            LocaliiiyLanguage.TR to "Gönderiyi Öne Çıkar / Reklam Ver",
            LocaliiiyLanguage.SW to "Kuzza Chapisho / Tangaza",
            LocaliiiyLanguage.VI to "Quảng cáo bài viết / Chạy ads",
            LocaliiiyLanguage.UR to "پوسٹ کو فروغ دیں / اشتہار چلائیں"
        ),
        LocaliiiyStringKey.SPONSORED_LABEL to mapOf(
            LocaliiiyLanguage.EN to "Sponsored • Ad",
            LocaliiiyLanguage.ES to "Patrocinado • Publicidad",
            LocaliiiyLanguage.FR to "Sponsorisé • Publicité",
            LocaliiiyLanguage.DE to "Gesponsert • Anzeige",
            LocaliiiyLanguage.HI to "प्रायोजित • विज्ञापन",
            LocaliiiyLanguage.ZH to "赞助 • 广告",
            LocaliiiyLanguage.JA to "スポンサー • 広告",
            LocaliiiyLanguage.PT to "Patrocinado • Anúncio",
            LocaliiiyLanguage.AR to "مُموَّل • إعلان",
            LocaliiiyLanguage.RU to "Реклама • Спонсор",
            LocaliiiyLanguage.BN to "বিজ্ঞাপন • স্পনসর",
            LocaliiiyLanguage.ID to "Disponsori • Iklan",
            LocaliiiyLanguage.KO to "스폰서 • 광고",
            LocaliiiyLanguage.IT to "Sponsorizzato • Annuncio",
            LocaliiiyLanguage.TR to "Sponsorlu • Reklam",
            LocaliiiyLanguage.SW to "Imedhaminiwa • Tangazo",
            LocaliiiyLanguage.VI to "Được tài trợ • Quảng cáo",
            LocaliiiyLanguage.UR to "اسپانسر شدہ • اشتہار"
        ),
        LocaliiiyStringKey.CURRENCY_AND_LANG to mapOf(
            LocaliiiyLanguage.EN to "Language & Currency",
            LocaliiiyLanguage.ES to "Idioma y Moneda",
            LocaliiiyLanguage.FR to "Langue et Devise",
            LocaliiiyLanguage.DE to "Sprache & Währung",
            LocaliiiyLanguage.HI to "भाषा और मुद्रा",
            LocaliiiyLanguage.ZH to "语言与货币",
            LocaliiiyLanguage.JA to "言語と通貨",
            LocaliiiyLanguage.PT to "Idioma e Moeda",
            LocaliiiyLanguage.AR to "اللغة والعملة",
            LocaliiiyLanguage.RU to "Язык и валюта",
            LocaliiiyLanguage.BN to "ভাষা ও মুদ্রা",
            LocaliiiyLanguage.ID to "Bahasa & Mata Uang",
            LocaliiiyLanguage.KO to "언어 및 통화",
            LocaliiiyLanguage.IT to "Lingua e Valuta",
            LocaliiiyLanguage.TR to "Dil ve Para Birimi",
            LocaliiiyLanguage.SW to "Lugha na Sarafu",
            LocaliiiyLanguage.VI to "Ngôn ngữ & Tiền tệ",
            LocaliiiyLanguage.UR to "زبان اور کرنسی"
        )
    )

    fun getString(key: LocaliiiyStringKey, lang: LocaliiiyLanguage): String {
        return translations[key]?.get(lang)
            ?: translations[key]?.get(LocaliiiyLanguage.EN)
            ?: key.name
    }
}
